### ISSUE TITLE
Buttons on iOs

### ISSUE THREAD

**Issue by axecopfire** [theClubhouse-Augusta/theClubhou.se#22]
![Image from iOS](https://user-images.githubusercontent.com/24581531/59451226-fbe43480-8dd8-11e9-8160-2defe2c9fde7.png)

**Comment by Feevah** [comment]
I think that I've fixed the other bug, so I'm going to work on this one now, ok?

**Comment by Timestorm** [comment]
Upon checking the production site as of this morning, the buttons did seem functional on IOS.  Currently don't have my phone to test, can I get someone to verify this?

**Comment by ep-aia** [comment]
The buttons are better and show in the correct font, but the font is very small and difficult to read.

**Comment by Timestorm** [comment]
@EricClubhouse The font is displaying fine on my iPhone 8S.  But I noticed that in PC browsers the font runs together.  I opened a new issue #43

![image1](https://user-images.githubusercontent.com/2022576/59546799-136b0c80-8f02-11e9-809d-c0d8e8388d3b.png)

**Comment by axecopfire** [comment]
charge your phone @Timestorm

**Comment by Timestorm** [comment]
@axecopfire NO, we call it the SkyAgTech charge. And the font is now offset again.[
![78FE700D-10AD-4F00-ACAE-ACA0B74A5A63](https://user-images.githubusercontent.com/2022576/60101917-a12cd000-972a-11e9-9a61-bebbda0ac78b.png)
](url)
