### ISSUE TITLE
Update styles/HTML to use BEM

### ISSUE THREAD

**Issue by axecopfire** [theClubhouse-Augusta/theClubhou.se#23]
To make a stronger CSS architecture we should utilize the [BEM](http://getbem.com/) naming architecture.

**Comment by Timestorm** [comment]
Why was this closed, I don't see a pull request associated with this issue.

**Comment by axecopfire** [comment]
Due to inactivity and the project no longer being active in general.

**Comment by Timestorm** [comment]
Sooooo, it's not resolved then?

**Comment by axecopfire** [comment]
Correct, not resolved. But closed. U r more than welcome to submit a PR.

**Comment by Timestorm** [comment]
Cool, I'll open a new issue you can merge into this issue, reopeninging it so I can submit a pull request for the issues that's still an issue, but apparently a closed issue
